import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_components/Nav";
import Providers from "./redux/Provider";
import ContextApiData from "./ContexHookData/contextApidata";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         
      >
        <Providers>
        <ContextApiData> 
  
       <Nav/> 
        {children}
        </ContextApiData>
        </Providers>
      </body>
    </html>
  );
}
